import os
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, EmailStr
from typing import List, Optional
import uvicorn

app = FastAPI(
    title="AI Generated Cloud Product API",
    description="Engineered and generated by AI Product Architect",
    version="1.0.0"
)

# Cross-Origin Resource Sharing (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health", tags=["Monitoring"])
def health_check():
    return {"status": "healthy", "service": "backend-api", "version": "1.0.0"}

class ProductItem(BaseModel):
    id: str
    title: str
    price: float
    category: str
    in_stock: bool

@app.get("/api/products", response_model=List[ProductItem], tags=["Products"])
def list_products():
    return [
        {
            "id": "prod-001",
            "title": "Cloud Edge AI Compute Stick",
            "price": 7499.0,
            "category": "Cloud Electronics",
            "in_stock": True
        },
        {
            "id": "prod-002",
            "title": "Ergonomic DevOps Keyboard",
            "price": 12999.0,
            "category": "Developer Tools",
            "in_stock": True
        }
    ]

@app.post("/api/auth/login", tags=["Auth"])
def login_user(credentials: dict):
    # Authenticates customer and returns signed JWT
    if credentials.get("email") and credentials.get("password"):
        return {
            "access_token": "mock-jwt-token-ai-architect-signed",
            "token_type": "bearer",
            "user": {
                "name": "Cloud Engineer",
                "email": credentials.get("email")
            }
        }
    raise HTTPException(status_code=400, detail="Invalid login credentials")

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
