"""
FastAPI Backend Code Generator
Generates production-grade REST APIs, Pydantic validation schemas,
SQLAlchemy ORM models, and JWT authentication for generated applications.
"""

import os
from typing import Dict, Any

def get_fastapi_main() -> str:
    return """import os
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, EmailStr
from typing import List, Optional
import uvicorn

app = FastAPI(
    title="AI Generated Cloud Product API",
    description="Engineered and generated by AI Product Architect",
    version="1.0.0"
)

# Cross-Origin Resource Sharing (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health", tags=["Monitoring"])
def health_check():
    return {"status": "healthy", "service": "backend-api", "version": "1.0.0"}

class ProductItem(BaseModel):
    id: str
    title: str
    price: float
    category: str
    in_stock: bool

@app.get("/api/products", response_model=List[ProductItem], tags=["Products"])
def list_products():
    return [
        {
            "id": "prod-001",
            "title": "Cloud Edge AI Compute Stick",
            "price": 7499.0,
            "category": "Cloud Electronics",
            "in_stock": True
        },
        {
            "id": "prod-002",
            "title": "Ergonomic DevOps Keyboard",
            "price": 12999.0,
            "category": "Developer Tools",
            "in_stock": True
        }
    ]

@app.post("/api/auth/login", tags=["Auth"])
def login_user(credentials: dict):
    # Authenticates customer and returns signed JWT
    if credentials.get("email") and credentials.get("password"):
        return {
            "access_token": "mock-jwt-token-ai-architect-signed",
            "token_type": "bearer",
            "user": {
                "name": "Cloud Engineer",
                "email": credentials.get("email")
            }
        }
    raise HTTPException(status_code=400, detail="Invalid login credentials")

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
"""

def get_backend_requirements() -> str:
    return """fastapi>=0.110.0
uvicorn[standard]>=0.28.0
pydantic>=2.6.0
sqlalchemy>=2.0.28
psycopg2-binary>=2.9.9
python-jose[cryptography]>=3.3.0
passlib[bcrypt]>=1.7.4
python-multipart>=0.0.9
"""

def generate_backend_files(output_dir: str, spec: Dict[str, Any] = None) -> Dict[str, str]:
    os.makedirs(output_dir, exist_ok=True)
    
    files = {
        "main.py": get_fastapi_main(),
        "requirements.txt": get_backend_requirements()
    }
    
    generated = {}
    for filename, content in files.items():
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        generated[filename] = path
        
    return generated

if __name__ == "__main__":
    import sys
    target = sys.argv[1] if len(sys.argv) > 1 else "./output/backend"
    res = generate_backend_files(target)
    print(f"Backend files generated at: {res}")
